import 'package:flutter/material.dart';
import 'app.dart';
import 'core/di/injection_container.dart';

// Generated by FlutterFire CLI - run `flutterfire configure` to create this file
// import 'config/firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Firebase - uncomment after running `flutterfire configure`
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  await initDependencies();

  runApp(const App());
}
